# Generated by Django 3.0.4 on 2020-04-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0003_video_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
