# Generated by Django 3.0.4 on 2020-05-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0004_user_paid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paypal_order_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='paypal_subscription_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
