# Generated by Django 3.0.4 on 2020-05-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0005_user_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='pro',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
