# Generated by Django 3.0.4 on 2020-04-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0006_stripesubscription_customer_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StripeCustomer',
        ),
        migrations.DeleteModel(
            name='StripeSubscription',
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
